FROM golang:1.17-alpine3.15 as builder
WORKDIR /go/src
COPY app/ .
RUN go install -v ./... \
    && go build \
    && go clean -cache \
    && go clean -testcache \
   && go clean -r      

FROM scratch

COPY --from=builder /go/bin/hello /go/bin/hello

ENTRYPOINT ["/go/bin/hello"]



