FROM golang:1.17-alpine3.15 as builder
WORKDIR /go/src
COPY app/ .
RUN go install -v ./... \
    && go build \
    && go clean -cache \
    && go clean -testcache \
   && go clean -r      

FROM golang:1.17-alpine3.15
WORKDIR /go/src
COPY --from=builder /go/bin /go/bin

ENTRYPOINT [ "hello" ]



